language: node_js
node_js:
 - "7"

before_install:
  - chmod +x testing.sh
  - chmod +x deploy.sh

script:
  - ./testing.sh

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  script:
    - ./deploy.sh
  on:
    branch: master